### PR TITLE
Update macOS/xcode environments on CircleCI

### LINKED ISSUE #470: CircleCI macOS jobs are configured to use Xcode versions that are no longer available
macOS jobs on CircleCI fail immediately with errors of the following form:

`Job was rejected because resource class macos.m1.medium.gen1, image xcode:12.5.1 is not a valid resource class `

CircleCI configuration should be updated to use a newer xcode version (and/or macOS environment generally).

### PR DESCRIPTION
**Pull request by crwood**
Closes #470

### CODE REVIEW

**Comment by crwood** [comment]
Broken as a result of `$CIRCLE_BRANCH` pointing (in this case) to `pull/471` instead of to `470.update-circleci-xcode` (introduced by https://github.com/PrivateStorageio/ZKAPAuthorizer/pull/467).

cc @btlogy

**Review by hacklschorsch — APPROVED** [review]
LGTM!

**Review by btlogy — APPROVED** [review]
LGTM, but probably interesting to rebase/merge once #473 lands main.

**Comment by crwood** [comment]
The failures above are unrelated to this PR; merging.

**Pull request merged**
