### PR TITLE
Drop support for Tahoe-LAFS version 1.17.1

### LINKED ISSUE #468: Drop Tahoe-LAFS version 1.17
Tahoe-LAFS version 1.17 is quite old and is not being used by either the PrivateStorage client or the PrivateStorage server (which use 1.18). Consider dropping support/testing for 1.17 as a step towards supporting newer versions -- and saving some CI credits along the way.

### PR DESCRIPTION
**Pull request by crwood**
Closes #468

### CODE REVIEW

**Comment by crwood** [comment]
Broken as a result of `$CIRCLE_BRANCH` pointing (in this case) to `pull/469` instead of to `468.drop-tahoe-1.17` (introduced by https://github.com/PrivateStorageio/ZKAPAuthorizer/pull/467).

cc @btlogy

**Review by hacklschorsch — APPROVED** [review]
LGTM!

**Review by btlogy — APPROVED** [review]
LGTM, but probably interesting to rebase/merge once #473 lands main.

**Comment by crwood** [comment]
The failures above are unrelated to this PR; merging.

**Pull request merged**
